NAME=BH14505_chimera letter_to_editor
VIEWPDF=evince
BIBTEXSRCS=chimera_refs.bib
USE_PDFLATEX=1
CLEAN_FILES+=*.synctex.gz B14505_chimeraNotes.bib BH14505_chimera.tar.gz *.bak *.tmp

include /usr/share/latex-mk/latex.gmk
